import type { Meta, StoryObj } from '@storybook/vue3';
import HotLeadFormPresentational from '../vweb/common/components/mvthotleadform/hotlead.presentational.vue';

const meta: Meta = {
    title: 'General/Hotlead Card',
    component: HotLeadFormPresentational,
    tags: ['autodocs'],
    argTypes: {},
    args: {
        profile: '',
        hotlead: {
            comment: '',
            phone: '',
            enquiryType: '',
            name: '',
            email: '',
            moveIn: '',
            price: '',
            veteransType: '',
            zipcode: '',
        },
        options: {
            propertyData: {
                isRentals: true,
            },
            profileHighlighter: '',
            enableChangeDate: true,
            buttonClass: '',
        },
        title: '',
        subtitle: '',
        formClass: '',
        submitForm: () => alert('submitForm clicked'),
        leadForm: {
            showOJOagentInfo: true,
            showCtaLinks: true,
            commnetLabel: '',
            showDisclaimer: true,
        },
        enquiryInput: '',
        enquiryData: [],
        leadChecklist: [],
        moveDate: '',
        errorMessage: '',
        assignedAgentCtaLinks: [
            { text: '', value: '' },
            { text: '', value: '' },
        ],
        activeCTAIndex: 0,
        hasDefaultPhone: false,
        isACForm: true,
        glb: {
            user: {
                fullName: '',
                email: '',
                phone: '',
            },
        },
        editFullName: true,
        editEmail: true,
        editPhone: true,
        showAddress: false,
        showZipcode: true,
        showInputGeo: true,
        forceInputPrice: false,
        showComment: false,
        isVeteran: false,
        getVeteranCheckboxData: {
            label: '',
            value: false,
        },
        showVeteransType: true,
        veteransTypeData: [],
        visiableDisclaimer: true,
        leadDisclaimer: '',
        popDialogBox: false,
        buttonText: '',
        formattedPhone: '',
        labels: {
            phoneInput: '',
            name: '',
            buySellComments: '',
            comments: '',
            ojoLeadFormDisclaimer: '',
            email: '',
            zipcode: '',
        },
        showConcierge: false,
        showVeteransOption: false,
        errorMsg: '',
        disableSend: false,
        addressInput: {},
        localCalendar: '',
        updateCalendar: () => alert('updateCalendar clicked'),
        hasOJOAgent: false,
        acFormLeadType: '',
        showStreetView: false,
        showConfirmUI: false,
        showConfirmTitle: false,
        propertyData: {
            geo: {
                lat: '',
                lng: '',
                address:'',
            }
        }
    },
};

export default meta;
type Story = StoryObj<typeof HotLeadFormPresentational>;

export const Default: Story = {
    args: {
        profile: '',
        hotlead: {
            comment: '',
            phone: '',
            enquiryType: '',
            name: '',
            email: '',
            moveIn: '',
            price: '',
            veteransType: '',
        },
        options: {
            propertyData: {
                isRentals: true,
            },
            profileHighlighter: '',
            enableChangeDate: true,
            buttonClass: '',
        },
        title: 'Connect with an Agent',
        subtitle: 'We will match you with a top local Real Estate agent best suited to your home journey needs.',
        formClass: '',
        submitForm: () => alert('submitForm clicked'),
        leadForm: {
            showOJOagentInfo: true,
            showCtaLinks: true,
            commnetLabel: '',
            showDisclaimer: true,
        },
        enquiryInput: '',
        enquiryData: [],
        leadChecklist: [],
        moveDate: '',
        errorMessage: '',
        assignedAgentCtaLinks: [],
        activeCTAIndex: 1,
        hasDefaultPhone: false,
        isACForm: true,
        glb: {
            user: {
                fullName: '',
                email: '',
                phone: '',
            },
        },
        editFullName: true,
        editEmail: true,
        editPhone: true,
        showAddress: false,
        showZipcode: true,
        showInputGeo: true,
        forceInputPrice: false,
        showComment: false,
        isVeteran: false,
        getVeteranCheckboxData: {
            label: '',
            value: false,
        },
        showVeteransType: true,
        veteransTypeData: [],
        visiableDisclaimer: true,
        leadDisclaimer:
            'By submitting your information, you agree Movoto can share your information with its network of real estate & mortgage professionals (affiliates) (or through their agents) and consent to receive marketing emails, calls, & texts related to your inquiry (including via automatic telephone dialing system, or artificial or pre-recorded voice technology) from Movoto or affiliates to the email address or number you provided even if your number appears on the company, state, or national Do Not Call Registry. You further agree that such affiliates may share information with Movoto and each other. You also agree to our Terms & Conditions and Privacy Policy. Consent not required for purchase.',
        popDialogBox: false,
        buttonText: 'Connect Now',
        formattedPhone: '',
        labels: {
            phoneInput: 'Mobile Phone',
            name: 'Name',
            buySellComments: '',
            comments: '',
            ojoLeadFormDisclaimer: '',
            email: 'Email',
            zipcode: 'Zip Code',
        },
        showConcierge: false,
        showVeteransOption: false,
        errorMsg: '',
        disableSend: false,
        addressInput: {},
        localCalendar: '',
        updateCalendar: () => alert('updateCalendar clicked'),
        hasOJOAgent: false,
        acFormLeadType: '',
        showStreetView: false,
        showConfirmUI: false,
        showConfirmTitle: false,
        propertyData: {
            geo: {
                lat: '',
                lng: '',
                address:'',
            }
        }
    },
};
